version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mirakc-epgstation/docker/debian"
    schedule:
      interval: "weekly"
